services:
  - docker
language: python
python:
  - "3.7"
# command to run tests
script:
  - docker build . -t myimage
  - packages=$(cat test_packages)
  - failed=""
  - error=0
  - for i in $packages; do   docker run myimage sh buildscript.sh $i;   if [ "$?" -ne 0 ];   then error=1;   failed="$failed $i,";   fi; done
  - echo "failed packages $failed"
  - exit $error


