[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython",
    "numpy",
]
requires-fedora = [
    'openblas-devel',
    'fftw-devel',
    'blas-devel',
    'lapack-devel',
    'suitesparse-devel',
    'gcc-gfortran',
    'swig',
    'gcc-c++',
    'qhull-devel',
    'python3-f2py',
]